plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.4'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.9.4' // [추가] proto -> java/gRPC 코드 생성 플러그인
}

group = 'com.playtab'
version = '0.0.1-SNAPSHOT'
description = 'contentservice'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// gRPC Server (Spring Boot)
	implementation 'net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE'

	// Protobuf / gRPC
	implementation platform("io.grpc:grpc-bom:1.66.0")
	implementation 'io.grpc:grpc-protobuf'
	implementation 'io.grpc:grpc-stub'
	implementation 'io.grpc:grpc-netty-shaded'
	compileOnly 'org.apache.tomcat:annotations-api:6.0.53' // [추가] generated 코드에서 필요할 수 있음

	// DB
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.flywaydb:flyway-core'
	runtimeOnly 'org.postgresql:postgresql'

	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation "com.google.protobuf:protobuf-java-util:3.25.3"

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

protobuf { // proto 코드 생성 설정
	protoc {
		artifact = "com.google.protobuf:protoc:3.25.3"
	}
	plugins {
		grpc {
			artifact = "io.grpc:protoc-gen-grpc-java:1.66.0"
		}
	}
	generateProtoTasks {
		all().each { task ->
			task.plugins {
				grpc {}
			}
		}
	}
}

sourceSets { // 생성된 소스 디렉토리를 자바 소스로 인식
	main {
		java {
			srcDirs += [
					'build/generated/source/proto/main/java',
					'build/generated/source/proto/main/grpc'
			]
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}